server:
  port: ${SVC-A-PORT:8080}
spring:
  zipkin:
    base-url: http://${ZIPKIN-HOST:localhost}:${ZIPKIN-PORT:9411}/
  sleuth:
    sampler:
      probability: 1

cloud:
  k8s:
    x-trace-id:
      enabled: true