server:
  port: ${A_SVC_PORT:8080}
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1

management:
  info:
    kubernetes:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true