server:
  port: ${B_SVC_PORT:8080}
spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1

cloud:
  k8s:
    x-trace-id:
      enabled: true