apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-a
  namespace: cloud-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
      - name: svc-a
        image: svc-a:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        env:
          - name: SVC-B-HOST
            valueFrom:
              configMapKeyRef:
                name: svc-config-map
                key: SVC-B-HOST
          - name: SVC-D-HOST
            valueFrom:
              configMapKeyRef:
                name: svc-config-map
                key: SVC-D-HOST
          - name: ZIPKIN-HOST
            valueFrom:
              configMapKeyRef:
                name: svc-config-map
                key: ZIPKIN-HOST