apiVersion: v1
kind: Service
metadata:
  name: svc-c
  namespace: cloud-k8s
  labels:
    app: svc-c
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    protocol: TCP
    port: 8080
  selector:
    app: svc-c
