apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-c
  namespace: cloud-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-c
  template:
    metadata:
      labels:
        app: svc-c
    spec:
      containers:
      - name: svc-c
        image: svc-c:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        env:
          - name: ZIPKIN_HOST
            valueFrom:
              configMapKeyRef:
                name: svc-config-map
                key: ZIPKIN_HOST